'use strict'
const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('api', {
  openVideo: () => ipcRenderer.invoke('open-video'),
  openAudio: () => ipcRenderer.invoke('open-audio'),
  fileUrl: (p) => ipcRenderer.invoke('file-url', p),
  openProject: () => ipcRenderer.invoke('open-project'),
  openProjectPath: (p) => ipcRenderer.invoke('open-project-path', p),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  probeEncoder: () => ipcRenderer.invoke('probe-encoder'),
  probeFps: (p) => ipcRenderer.invoke('probe-fps', p),
  probeAudioTracks: (p) => ipcRenderer.invoke('probe-audio-tracks', p),
  detectScenes: (opts) => ipcRenderer.invoke('detect-scenes', opts),
  detectCancel: () => ipcRenderer.invoke('detect-cancel'),
  onDetectProgress: (cb) => ipcRenderer.on('detect-progress', (e, n) => cb(n)),
  ensureProxy: (src) => ipcRenderer.invoke('ensure-proxy', src),
  cancelProxy: () => ipcRenderer.invoke('cancel-proxy'),
  clearProxyCache: () => ipcRenderer.invoke('clear-proxy-cache'),
  onProxyProgress: (cb) => ipcRenderer.on('proxy-progress', (e, n) => cb(n)),
  extractAudioTrack: (p, i) => ipcRenderer.invoke('extract-audio-track', p, i),
  extractAudioPlay: (p, i) => ipcRenderer.invoke('extract-audio-play', p, i),
  saveProject: (json, p) => ipcRenderer.invoke('save-project', json, p),
  saveProjectAs: (json, p) => ipcRenderer.invoke('save-project-as', json, p),
  importSrt: () => ipcRenderer.invoke('import-srt'),
  importSubs: () => ipcRenderer.invoke('import-subs'),
  pickFont: () => ipcRenderer.invoke('pick-font'),
  exportSrt: (content, suggested) => ipcRenderer.invoke('export-srt', content, suggested),
  importDetx: () => ipcRenderer.invoke('import-detx'),
  exportDetx: (content, suggested) => ipcRenderer.invoke('export-detx', content, suggested),
  exportPdf: (html, suggested) => ipcRenderer.invoke('export-pdf', html, suggested),
  setDirty: (d) => ipcRenderer.invoke('set-dirty', d),
  confirmUnsaved: () => ipcRenderer.invoke('confirm-unsaved'),
  setUndoState: (st) => ipcRenderer.invoke('set-undo-state', st),
  readFile: (p) => ipcRenderer.invoke('read-file', p),
  statFile: (p) => ipcRenderer.invoke('file-stat', p),
  saveTake: (projectPath, name, buf) => ipcRenderer.invoke('save-take', projectPath, name, buf),
  takeUrl: (projectPath, name) => ipcRenderer.invoke('take-url', projectPath, name),
  deleteTake: (projectPath, name) => ipcRenderer.invoke('delete-take', projectPath, name),
  whisperStatus: (model) => ipcRenderer.invoke('whisper-status', model),
  whisperPickExe: () => ipcRenderer.invoke('whisper-pick-exe'),
  whisperClearExe: () => ipcRenderer.invoke('whisper-clear-exe'),
  whisperListModels: () => ipcRenderer.invoke('whisper-list-models'),
  whisperRevealDir: () => ipcRenderer.invoke('whisper-reveal-dir'),
  whisperDownloadModel: (model) => ipcRenderer.invoke('whisper-download-model', model),
  whisperDeleteModel: (model) => ipcRenderer.invoke('whisper-delete-model', model),
  whisperCancel: () => ipcRenderer.invoke('whisper-cancel'),
  whisperTranscribe: (opts) => ipcRenderer.invoke('whisper-transcribe', opts),
  onWhisperProgress: (cb) => ipcRenderer.on('whisper-progress', (e, p) => cb(p)),
  pickExecutable: () => ipcRenderer.invoke('pick-executable'),
  pickDirectory: () => ipcRenderer.invoke('pick-directory'),
  sepDefaultDir: (projectPath) => ipcRenderer.invoke('sep-default-dir', projectPath),
  audioConfigGet: () => ipcRenderer.invoke('audio-config-get'),
  audioConfigSet: (cfg) => ipcRenderer.invoke('audio-config-set', cfg),
  listCaptureDevices: (api, ff) => ipcRenderer.invoke('list-capture-devices', api, ff),
  captureStart: (opts) => ipcRenderer.invoke('capture-start', opts),
  captureStop: () => ipcRenderer.invoke('capture-stop'),
  sepConfigGet: () => ipcRenderer.invoke('sep-config-get'),
  sepConfigSet: (cfg) => ipcRenderer.invoke('sep-config-set', cfg),
  sepListModels: () => ipcRenderer.invoke('sep-list-models'),
  sepInstallModel: (file) => ipcRenderer.invoke('sep-install-model', file),
  sepDeleteModel: (file) => ipcRenderer.invoke('sep-delete-model', file),
  detectPython: () => ipcRenderer.invoke('detect-python'),
  sepRun: (opts) => ipcRenderer.invoke('sep-run', opts),
  sepCancel: () => ipcRenderer.invoke('sep-cancel'),
  onSepProgress: (cb) => ipcRenderer.on('sep-progress', (e, p) => cb(p)),
  pathForFile: (f) => webUtils.getPathForFile(f),
  onMenu: (cb) => ipcRenderer.on('menu', (e, action, arg) => cb(action, arg)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, v) => cb(v)),
  openReleases: () => ipcRenderer.invoke('open-releases'),
  setLang: (o) => ipcRenderer.invoke('set-lang', o),
  discordActivity: (a) => ipcRenderer.invoke('discord-activity', a),
  exportSaveDialog: (suggested) => ipcRenderer.invoke('export-save-dialog', suggested),
  exportStart: (opts) => ipcRenderer.invoke('export-start', opts),
  exportFrame: (buf) => ipcRenderer.invoke('export-frame', buf),
  exportEnd: () => ipcRenderer.invoke('export-end'),
  exportCancel: () => ipcRenderer.invoke('export-cancel'),
  onExportProgress: (cb) => ipcRenderer.on('export-progress', (e, n) => cb(n)),
  onExportClosed: (cb) => ipcRenderer.on('export-closed', (e, code, err) => cb(code, err)),
})
