'use strict'
const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('api', {
  openVideo: () => ipcRenderer.invoke('open-video'),
  openAudio: () => ipcRenderer.invoke('open-audio'),
  fileUrl: (p) => ipcRenderer.invoke('file-url', p),
  openProject: () => ipcRenderer.invoke('open-project'),
  openProjectPath: (p) => ipcRenderer.invoke('open-project-path', p),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  probeEncoder: () => ipcRenderer.invoke('probe-encoder'),
  probeFps: (p) => ipcRenderer.invoke('probe-fps', p),
  probeAudioTracks: (p) => ipcRenderer.invoke('probe-audio-tracks', p),
  extractAudioTrack: (p, i) => ipcRenderer.invoke('extract-audio-track', p, i),
  saveProject: (json, p) => ipcRenderer.invoke('save-project', json, p),
  saveProjectAs: (json, p) => ipcRenderer.invoke('save-project-as', json, p),
  importSrt: () => ipcRenderer.invoke('import-srt'),
  exportSrt: (content, suggested) => ipcRenderer.invoke('export-srt', content, suggested),
  importDetx: () => ipcRenderer.invoke('import-detx'),
  exportDetx: (content, suggested) => ipcRenderer.invoke('export-detx', content, suggested),
  exportPdf: (html, suggested) => ipcRenderer.invoke('export-pdf', html, suggested),
  setDirty: (d) => ipcRenderer.invoke('set-dirty', d),
  confirmUnsaved: () => ipcRenderer.invoke('confirm-unsaved'),
  setUndoState: (st) => ipcRenderer.invoke('set-undo-state', st),
  readFile: (p) => ipcRenderer.invoke('read-file', p),
  statFile: (p) => ipcRenderer.invoke('file-stat', p),
  pathForFile: (f) => webUtils.getPathForFile(f),
  onMenu: (cb) => ipcRenderer.on('menu', (e, action, arg) => cb(action, arg)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, v) => cb(v)),
  openReleases: () => ipcRenderer.invoke('open-releases'),
  setLang: (o) => ipcRenderer.invoke('set-lang', o),
  discordActivity: (a) => ipcRenderer.invoke('discord-activity', a),
  exportSaveDialog: (suggested) => ipcRenderer.invoke('export-save-dialog', suggested),
  exportStart: (opts) => ipcRenderer.invoke('export-start', opts),
  exportFrame: (buf) => ipcRenderer.invoke('export-frame', buf),
  exportEnd: () => ipcRenderer.invoke('export-end'),
  exportCancel: () => ipcRenderer.invoke('export-cancel'),
  onExportProgress: (cb) => ipcRenderer.on('export-progress', (e, n) => cb(n)),
  onExportClosed: (cb) => ipcRenderer.on('export-closed', (e, code, err) => cb(code, err)),
})
